<HTML>
<HEAD>
<meta charset="UTF-8">
<title>HibernateCallback.doInHibernate - spring-framework</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">spring-framework</a>&nbsp;/&nbsp;<a href="../index.html">org.springframework.orm.hibernate5</a>&nbsp;/&nbsp;<a href="index.html">HibernateCallback</a>&nbsp;/&nbsp;<a href=".">doInHibernate</a><br/>
<br/>
<h1>doInHibernate</h1>
<a name="org.springframework.orm.hibernate5.HibernateCallback$doInHibernate(org.hibernate.Session)"></a>
<code><span class="identifier">@Nullable</span> <span class="keyword">abstract</span> <span class="keyword">fun </span><span class="identifier">doInHibernate</span><span class="symbol">(</span><span class="identifier" id="org.springframework.orm.hibernate5.HibernateCallback$doInHibernate(org.hibernate.Session)/session">session</span><span class="symbol">:</span>&nbsp;<span class="identifier">Session</span><span class="symbol">)</span><span class="symbol">: </span><span class="identifier">T</span></code>
<p>Gets called by <code>HibernateTemplate.execute</code> with an active Hibernate <code>Session</code>. Does not need to care about activating or closing the <code>Session</code>, or handling transactions. 
<p>Allows for returning a result object created within the callback, i.e. a domain object or a collection of domain objects. A thrown custom RuntimeException is treated as an application exception: It gets propagated to the caller of the template.</p>
</p>
<h3>Parameters</h3>
<p><a name="session"></a>
<code>session</code> - active Hibernate session</p>
<h3>Exceptions</h3>
<p><a name="HibernateException"></a>
<code>HibernateException</code> - if thrown by the Hibernate API</p>
<p><strong>Return</strong><br/>
a result object, or <code>null</code> if none</p>
<p><strong>See Also</strong><br/>
<a href="#">HibernateTemplate#execute</a></p>
</BODY>
</HTML>
